version: '3.9'
services:
    redis:
        image: redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redis_data_a:/data
        entrypoint: redis-server --appendonly yes --requirepass redis
    
volumes:
    redis_data_a:

networks:
  default:
    name: redis_network
